# Ejercicio: Investigar y ejemplificar diferencias entre np.array y np.matrix

La diferencia entre una array y una matrix, es que la matriz es que son extrictamente bidimensionales y el array es solamente un arreglo o lista de numeros, ambos se pueden operar y trasnponer.

Si deseamos utilizar una matriz 3D o de tres dimensiones esto se convertiria en un ndarray en este caso seguiria siendo un array , entonces podriamos decir que un array es "n"-dimensional

In [66]:
import numpy as np

a = np.matrix('4 3; 2 1')

print(a)

[[4 3]
 [2 1]]


In [67]:
import numpy as np
b = np.array([1,2,3])
print(b)

[1 2 3]


In [71]:
np.ndarray(shape=(2,3), dtype=float, order='F')

array([[0.62430556, 0.62430556, 5.27430556],
       [0.33611111, 3.35611111, 0.33611111]])